export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const TUBING_PRESSURE_RECEIVED = "EVENT/TUBING_PRESSURE_RECEIVED";
export const CASING_PRESSURE_RECEIVED = "EVENT/CASING_PRESSURE_RECEIVED";
export const OIL_TEMP_RECEIVED = "EVENT/OIL_TEMP_RECEIVED";
export const FLARE_TEMP_RECEIVED = "EVENT/FLARE_TEMP_RECEIVED";
export const WATER_TEMP_RECEIVED = "EVENT/WATER_TEMP_RECEIVED";
export const INJVALVE_OPEN_RECEIVED = "EVENT/INJVALVE_OPEN_RECEIVED";

